services:
  frontend:
    build: .
    ports:
      - "3039:3039"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true 