version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3035:80"
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_DATABASE=ai_stocks
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - mysql
    networks:
      - ai-stocks-network

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=ai_stocks
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=ai_stocks
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ai-stocks-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "3037:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - mysql
    networks:
      - ai-stocks-network

volumes:
  mysql_data:

networks:
  ai-stocks-network:
    driver: bridge 